mod abs_i32;
mod add_attacks_remaining;
mod add_barrier_fx_frame;
mod add_behemoth_dodge_timer;
mod add_burrow_count;
mod add_cannon_shot_id;
mod add_castle_anim_frame;
mod add_curse_timer;
mod add_death_timer;
mod add_deck_cooldown;
mod add_dodge_fx_frame;
mod add_dodge_timer;
mod add_drain_pct;
mod add_entity_frame;
mod add_freeze_timer;
mod add_hit_flash_timer;
mod add_hp;
mod add_kill_count;
mod add_medal_progress;
mod add_money;
mod add_orb_dodge_timer;
mod add_pos_x;
mod add_revive_count;
mod add_revive_timer;
mod add_score_hit_mask;
mod add_shield_fx_frame;
mod add_shockwave_counter;
mod add_slow_timer;
mod add_warp_timer;
mod add_weaken_timer;
mod advance_animation_frame;
mod aku_realm_final_redirect;
mod app_context;
mod asset_stream;
mod atan2_deg;
mod attack_ability_fields;
mod attack_damage_fields;
mod attack_dmg_dispatch;
mod attack_foreswing_fields;
mod attack_ld_anchor_fields;
mod attack_ld_flag_fields;
mod attack_ld_flag_store_fields;
mod attack_ld_span_fields;
mod attack_proc_dispatch;
mod award_event_points;
mod base_resists_one_shot;
mod base_shake_start;
mod base_shake_tick;
mod battle_event_priorities;
mod battle_not_finishing;
mod build_trait_mask;
mod call_rng;
mod can_push_back;
mod cannon_attack;
mod cannon_attack_dispatch;
mod cannon_fire;
mod cannon_hp_mode;
mod cannon_makes_wave;
mod cannon_reach_x;
mod cannon_shot_origin_x;
mod cannon_shot_spacing;
mod cannon_target_in_range;
mod cannon_unlocked;
mod cat_attack_dispatch;
mod cat_cpu_tick;
mod cat_hit_executor;
mod cat_update;
mod charagroup_has_unit;
mod check_collision;
mod compute_attack;
mod compute_back_bound;
mod compute_event_points;
mod compute_hp;
mod conjurer_on_field;
mod cos_deg;
mod count_target_traits;
mod counter_surge_update;
mod deck_slot_filled;
mod deploy_limit_reached;
mod deploy_part;
mod deploy_unit;
mod does_target;
mod enemy_attack_dispatch;
mod enemy_hit_executor;
mod enemy_schedule_tick;
mod enemy_update;
mod eoc_chapter_hp_mul;
mod event_items_count;
mod event_items_has;
mod ex_redirect_check_a;
mod ex_redirect_check_b;
mod ex_redirect_check_c;
mod ex_replacement_pending;
mod explosion_attack;
mod explosion_damage_defaults;
mod explosion_update;
mod explosion_width_defaults;
mod find_built_deck_4star;
mod find_point_rule_entry;
mod find_score_bonus;
mod get_altar_level_cap;
mod get_anim_len;
mod get_area_attack;
mod get_attack_cooldown;
mod get_attack_count;
mod get_attack_damage;
mod get_attack_end_mode;
mod get_attack_foreswing;
mod get_attack_interval;
mod get_attack_only;
mod get_attacks_remaining;
mod get_barrier_breaker_chance;
mod get_barrier_fx_active;
mod get_barrier_fx_frame;
mod get_barrier_hp;
mod get_barrier_state;
mod get_base_destroyer;
mod get_base_hp;
mod get_base_level;
mod get_base_max_hp;
mod get_base_max_hp_div_20;
mod get_base_pos_x;
mod get_base_pos_y;
mod get_base_shake_offset;
mod get_base_soulstrike;
mod get_base_upgrade;
mod get_battle_status;
mod get_behemoth_dodge_chance;
mod get_behemoth_dodge_duration;
mod get_behemoth_dodge_timer;
mod get_best_treasure;
mod get_boss_type;
mod get_boss_wave_immune;
mod get_built_deck_cannon;
mod get_built_deck_rows;
mod get_built_deck_stage_key;
mod get_burrow_count;
mod get_burrow_distance;
mod get_burrow_start_x;
mod get_button_unit_form;
mod get_button_unit_id;
mod get_button_unit_row;
mod get_cannon_base_damage;
mod get_cannon_blast_hit;
mod get_cannon_burrowed_permille;
mod get_cannon_charge_orb;
mod get_cannon_countdown;
mod get_cannon_damage;
mod get_cannon_decor_id;
mod get_cannon_effect;
mod get_cannon_foundation_id;
mod get_cannon_hit_stamp;
mod get_cannon_id;
mod get_cannon_metal_permille;
mod get_cannon_nonmetal_permille;
mod get_cannon_nonzombie_permille;
mod get_cannon_recharge;
mod get_cannon_save_value;
mod get_cannon_shot_id;
mod get_cannon_strike_width;
mod get_cannon_strike_x;
mod get_cannon_type;
mod get_cannon_unit_id;
mod get_cannon_wall_hp_pct;
mod get_cannon_wall_lifetime;
mod get_cannon_wall_offset;
mod get_cannon_zombie_permille;
mod get_cash_back_pct;
mod get_castle_anim_frame;
mod get_castle_anim_state;
mod get_castle_enemy_row;
mod get_castle_id;
mod get_castle_row;
mod get_cat_combo_bonus;
mod get_cat_combo_values;
mod get_cell;
mod get_cleared_count;
mod get_colossus_orb_atk_pct;
mod get_colossus_orb_def_pct;
mod get_column_count;
mod get_conjure_unit_id;
mod get_counter_surge;
mod get_counter_surge_once;
mod get_counter_surge_pct;
mod get_crit_fx;
mod get_critical_chance;
mod get_current_stage_id;
mod get_curse_chance;
mod get_curse_duration;
mod get_curse_immune;
mod get_curse_length;
mod get_curse_resist_pct;
mod get_curse_timer;
mod get_death_surge_anchor;
mod get_death_surge_level;
mod get_death_surge_mini;
mod get_death_surge_pct;
mod get_death_surge_span;
mod get_death_timer;
mod get_deck_cooldown;
mod get_deck_cooldown_max;
mod get_deploy_cost;
mod get_design_height2;
mod get_dodge_chance;
mod get_dodge_duration;
mod get_dodge_fx_frame;
mod get_dodge_timer;
mod get_drain_chance;
mod get_drain_immune;
mod get_drain_pct;
mod get_drain_percent;
mod get_effective_deploy_cost;
mod get_enemy_money_drop;
mod get_entity_base_idx;
mod get_entity_button;
mod get_entity_frame;
mod get_entity_state;
mod get_equipped_orb;
mod get_equipped_orbs;
mod get_ex_option_target;
mod get_explosion_anchor;
mod get_explosion_chance;
mod get_explosion_immune;
mod get_explosion_resist_pct;
mod get_explosion_span;
mod get_first_bounty_pct;
mod get_foundation_part_id;
mod get_foundation_part_level;
mod get_foundation_part_rec;
mod get_frame_damage;
mod get_freeze_chance;
mod get_freeze_duration;
mod get_freeze_immune;
mod get_freeze_length;
mod get_freeze_resist_pct;
mod get_freeze_timer;
mod get_global_map_id;
mod get_gudetama_soul;
mod get_hit_flash_timer;
mod get_hitbox_pos;
mod get_hp;
mod get_item_count;
mod get_kb_proc_hit;
mod get_kill_point_base;
mod get_knockback_chance;
mod get_knockback_immune;
mod get_knockback_resist_pct;
mod get_knockbacks;
mod get_ld_anchor;
mod get_ld_span;
mod get_listed_item_count;
mod get_map_cost_multiplier;
mod get_map_count;
mod get_map_index;
mod get_map_rules;
mod get_map_type;
mod get_max_hp;
mod get_max_money;
mod get_medal_progress;
mod get_metal_killer_fx;
mod get_metal_killer_pct;
mod get_mini_surge;
mod get_money;
mod get_money_increment;
mod get_no_revive;
mod get_occupant;
mod get_orb_dodge_chance;
mod get_orb_dodge_duration;
mod get_orb_dodge_timer;
mod get_orb_value_max;
mod get_orb_value_sum;
mod get_orb_value_vs_trait;
mod get_paid_cost;
mod get_point_rule;
mod get_point_rule_type;
mod get_pos_x;
mod get_pos_y;
mod get_powerup;
mod get_powerup_available;
mod get_preset_foundation_part;
mod get_preset_style_part;
mod get_prev_curse_timer;
mod get_prev_freeze_timer;
mod get_prev_slow_timer;
mod get_prev_weaken_timer;
mod get_proc_badge;
mod get_resist_part_rec;
mod get_revive_count;
mod get_revive_hp;
mod get_revive_time;
mod get_revive_timer;
mod get_sage_kb_resist_pct;
mod get_savage_blow_boost;
mod get_savage_blow_chance;
mod get_savage_blow_fx;
mod get_scene_id;
mod get_score_bonus;
mod get_score_hit_mask;
mod get_score_time_limit;
mod get_score_value;
mod get_setting;
mod get_shield_fx;
mod get_shield_fx_frame;
mod get_shield_hp;
mod get_shield_max;
mod get_shield_pierce_chance;
mod get_shield_regen;
mod get_shield_state;
mod get_shockwave_counter;
mod get_slot_unit_id;
mod get_slow_chance;
mod get_slow_duration;
mod get_slow_immune;
mod get_slow_length;
mod get_slow_resist_pct;
mod get_slow_timer;
mod get_soul_anim_type;
mod get_soulstrike;
mod get_spawn_anim_flag;
mod get_spawn_anim_type;
mod get_spawn_serial;
mod get_special_rule;
mod get_special_rule_params;
mod get_speed;
mod get_stage_count;
mod get_stage_index;
mod get_stage_record;
mod get_stage_set_size;
mod get_stages_cleared;
mod get_standing_range;
mod get_star_level;
mod get_star_multiplier;
mod get_stat_range;
mod get_status_bits;
mod get_strengthen_boost;
mod get_strengthen_threshold;
mod get_style_part_id;
mod get_style_part_level;
mod get_surge_anchor;
mod get_surge_chance;
mod get_surge_immune;
mod get_surge_level;
mod get_surge_resist_pct;
mod get_surge_span;
mod get_talent_icon_state;
mod get_talent_value;
mod get_tech_level;
mod get_took_damage;
mod get_total_damage_taken;
mod get_toxic_chance;
mod get_toxic_damage;
mod get_toxic_fx;
mod get_toxic_immune;
mod get_toxic_resist_pct;
mod get_trait_dojo;
mod get_trait_kaijin;
mod get_treasure_capped;
mod get_treasure_uncapped;
mod get_treasure_value;
mod get_unit_anim;
mod get_unit_form;
mod get_unit_max_level;
mod get_unit_model;
mod get_unit_name;
mod get_unit_rarity;
mod get_unit_recharge;
mod get_warp_anchor;
mod get_warp_chance;
mod get_warp_distance;
mod get_warp_duration;
mod get_warp_immune;
mod get_warp_resist_pct;
mod get_warp_span;
mod get_warp_timer;
mod get_wave_block;
mod get_wave_chance;
mod get_wave_hit_faction;
mod get_wave_immune;
mod get_wave_level;
mod get_wave_mini;
mod get_wave_resist_pct;
mod get_weaken_active;
mod get_weaken_active_pct;
mod get_weaken_chance;
mod get_weaken_duration;
mod get_weaken_immune;
mod get_weaken_pct;
mod get_weaken_resist_pct;
mod get_weaken_timer;
mod get_worker_level;
mod get_worker_upgrade_cost;
mod get_worker_upgrade_level;
mod get_zkill_hit;
mod has_attack_abilities;
mod has_barrier_breaker_chance;
mod has_base_curse_chance;
mod has_base_freeze_chance;
mod has_base_slow_chance;
mod has_behemoth_slayer;
mod has_built_deck;
mod has_cannon_ready_fx;
mod has_cannon_recoil;
mod has_castle_enemy;
mod has_colossus_slayer;
mod has_conjure_deck_slot;
mod has_critical_chance;
mod has_curse_chance;
mod has_double_bounty;
mod has_drain_chance;
mod has_eva_killer;
mod has_fixed_lineup;
mod has_freeze_chance;
mod has_insane_damage;
mod has_insanely_tough;
mod has_knockback_chance;
mod has_massive_damage;
mod has_orb;
mod has_resist;
mod has_sage_slayer;
mod has_savage_blow_chance;
mod has_shield_pierce_chance;
mod has_slow_chance;
mod has_strong_against;
mod has_talent;
mod has_toxic_chance;
mod has_warp_chance;
mod has_weaken_chance;
mod has_witch_slayer;
mod has_zombie_killer;
mod imgcut_get_cut_count;
mod imgcut_get_height;
mod imgcut_get_sprite_cut;
mod imgcut_get_width;
mod imgcut_load;
mod invasion_available;
mod invasion_z_available;
mod is_aku;
mod is_alien;
mod is_angel;
mod is_attack_long_range;
mod is_behemoth;
mod is_boss;
mod is_boss_guarding_base;
mod is_cannon_target;
mod is_colossus;
mod is_dark;
mod is_deploy_blocked;
mod is_eva_angel;
mod is_ex_map_68;
mod is_ex_option_target;
mod is_floating;
mod is_invasion_stage;
mod is_map_cleared;
mod is_metal;
mod is_outbreak_stage;
mod is_red;
mod is_relic;
mod is_sage;
mod is_score_stage;
mod is_scored_stage;
mod is_touchable;
mod is_touchable_thunk;
mod is_trait_targeted_talent;
mod is_traitless;
mod is_witch;
mod is_z_invasion_stage;
mod is_zombie;
mod keep_in_bound;
mod knockback_y_arc;
mod labyrinth_active;
mod latch_battle_event;
mod level_cell_base;
mod level_cell_plus;
mod load_cat_combat_csv;
mod load_cat_data_files;
mod load_enemy_castle_csv;
mod load_enemy_combat_csv;
mod load_stage_csv;
mod maanim_animate;
mod maanim_execute;
mod maanim_get_max_keyframe;
mod maanim_initialize;
mod maanim_load;
mod mamodel_get_anchor;
mod mamodel_get_anchor_part;
mod mamodel_get_anchor_x;
mod mamodel_get_anchor_y;
mod mamodel_load;
mod map_type_as_index;
mod map_type_base_id;
mod matrix_rotate;
mod matrix_set_translation;
mod matrix_translate;
mod max_i32;
mod min_i32;
mod no_more_attacks;
mod obf_value_read;
mod obf_value_read_2;
mod obfuscate_value;
mod orb_deploy_condition;
mod orb_deploy_condition_slot;
mod parse_stage_enemy_row;
mod pending_strike_hit;
mod play_sound;
mod play_sound_in_battle;
mod point_band_lookup;
mod proc_badge_fields;
mod proc_update;
mod read_asset_stream_line;
mod read_cell_stream;
mod read_csv_cell;
mod read_csv_row;
mod read_flag;
mod read_stream_row;
mod read_tsv_row;
mod recoil_y_arc;
mod recount_deploy_rarities;
mod rng;
mod roll_procs;
mod scored_map_pays_money;
mod set_area_attack;
mod set_attack_abilities;
mod set_attack_cooldown;
mod set_attack_damage;
mod set_attack_end_mode;
mod set_attack_foreswing;
mod set_attack_interval;
mod set_attack_only;
mod set_attacks_remaining;
mod set_barrier_breaker_chance;
mod set_barrier_fx_active;
mod set_barrier_fx_frame;
mod set_barrier_hp;
mod set_barrier_state;
mod set_base_curse_chance;
mod set_base_curse_duration;
mod set_base_destroyer;
mod set_base_entity_frame;
mod set_base_freeze_chance;
mod set_base_freeze_duration;
mod set_base_guard_notice;
mod set_base_hitbox_pos;
mod set_base_hitbox_width;
mod set_base_hp;
mod set_base_level;
mod set_base_max_hp;
mod set_base_occupant;
mod set_base_pos_x;
mod set_base_pos_y;
mod set_base_slow_chance;
mod set_base_slow_duration;
mod set_base_soulstrike;
mod set_base_state;
mod set_behemoth_dodge_chance;
mod set_behemoth_dodge_duration;
mod set_behemoth_dodge_timer;
mod set_behemoth_slayer;
mod set_boss_type;
mod set_boss_wave_immune;
mod set_burrow_count;
mod set_burrow_distance;
mod set_burrow_start_x;
mod set_cannon_base_damage;
mod set_cannon_blast_hit;
mod set_cannon_burrowed_permille;
mod set_cannon_charge_orb;
mod set_cannon_countdown;
mod set_cannon_damage;
mod set_cannon_hit_stamp;
mod set_cannon_hp_mode;
mod set_cannon_makes_wave;
mod set_cannon_metal_permille;
mod set_cannon_nonmetal_permille;
mod set_cannon_nonzombie_permille;
mod set_cannon_parts;
mod set_cannon_ready_fx;
mod set_cannon_recharge;
mod set_cannon_recoil;
mod set_cannon_shot_id;
mod set_cannon_strike_width;
mod set_cannon_strike_x;
mod set_cannon_type;
mod set_cannon_unit_id;
mod set_cannon_wall_hp_pct;
mod set_cannon_wall_lifetime;
mod set_cannon_wall_offset;
mod set_cannon_zombie_permille;
mod set_cash_back_pct;
mod set_castle_anim_frame;
mod set_castle_anim_state;
mod set_colossus_orb_pcts;
mod set_colossus_slayer;
mod set_conjure_deck_slot;
mod set_conjure_unit_id;
mod set_counter_surge;
mod set_counter_surge_once;
mod set_counter_surge_pct;
mod set_crit_fx;
mod set_critical_chance;
mod set_curse_chance;
mod set_curse_duration;
mod set_curse_immune;
mod set_curse_length;
mod set_curse_resist_pct;
mod set_curse_timer;
mod set_death_surge_anchor;
mod set_death_surge_chance;
mod set_death_surge_level;
mod set_death_surge_mini;
mod set_death_surge_pct;
mod set_death_surge_span;
mod set_death_timer;
mod set_deck_cooldown;
mod set_deck_cooldown_max;
mod set_dodge_chance;
mod set_dodge_duration;
mod set_dodge_fx_frame;
mod set_dodge_timer;
mod set_double_bounty;
mod set_drain_chance;
mod set_drain_immune;
mod set_drain_pct;
mod set_drain_percent;
mod set_entity_frame;
mod set_entity_state;
mod set_eva_killer;
mod set_explosion_anchor;
mod set_explosion_chance;
mod set_explosion_immune;
mod set_explosion_resist_pct;
mod set_explosion_span;
mod set_first_bounty_pct;
mod set_frame_damage;
mod set_freeze_chance;
mod set_freeze_duration;
mod set_freeze_immune;
mod set_freeze_length;
mod set_freeze_resist_pct;
mod set_freeze_timer;
mod set_gudetama_soul;
mod set_hit_flash_timer;
mod set_hitbox_pos;
mod set_hitbox_width;
mod set_hp;
mod set_insane_damage;
mod set_insanely_tough;
mod set_kb_proc_hit;
mod set_kill_count;
mod set_knockback_chance;
mod set_knockback_immune;
mod set_knockback_resist_pct;
mod set_knockbacks;
mod set_ld_anchor;
mod set_ld_flag;
mod set_ld_span;
mod set_massive_damage;
mod set_max_hp;
mod set_metal;
mod set_metal_killer_fx;
mod set_metal_killer_pct;
mod set_mini_surge;
mod set_money;
mod set_no_revive;
mod set_occupant;
mod set_orb_dodge_chance;
mod set_orb_dodge_duration;
mod set_orb_dodge_timer;
mod set_paid_cost;
mod set_pos_x;
mod set_pos_y;
mod set_powerup;
mod set_prev_curse_timer;
mod set_prev_freeze_timer;
mod set_prev_slow_timer;
mod set_prev_weaken_timer;
mod set_proc_badge;
mod set_resist;
mod set_revive_count;
mod set_revive_hp;
mod set_revive_time;
mod set_revive_timer;
mod set_sage_kb_resist_pct;
mod set_sage_slayer;
mod set_savage_blow_boost;
mod set_savage_blow_chance;
mod set_savage_blow_fx;
mod set_score_hit_mask;
mod set_score_value;
mod set_shield_fx;
mod set_shield_fx_frame;
mod set_shield_hp;
mod set_shield_max;
mod set_shield_pierce_chance;
mod set_shield_regen;
mod set_shield_state;
mod set_shockwave_counter;
mod set_slow_chance;
mod set_slow_duration;
mod set_slow_immune;
mod set_slow_length;
mod set_slow_resist_pct;
mod set_slow_timer;
mod set_soul_anim_type;
mod set_soulstrike;
mod set_spawn_anim_flag;
mod set_spawn_anim_type;
mod set_spawn_serial;
mod set_speed;
mod set_stage_entry_enemy;
mod set_standing_range;
mod set_strengthen_boost;
mod set_strengthen_threshold;
mod set_strong_against;
mod set_surge_anchor;
mod set_surge_chance;
mod set_surge_immune;
mod set_surge_level;
mod set_surge_resist_pct;
mod set_surge_span;
mod set_survive_chance;
mod set_total_damage_taken;
mod set_toxic_chance;
mod set_toxic_damage;
mod set_toxic_fx;
mod set_toxic_immune;
mod set_toxic_resist_pct;
mod set_trait_aku;
mod set_trait_alien;
mod set_trait_angel;
mod set_trait_behemoth;
mod set_trait_colossus;
mod set_trait_dark;
mod set_trait_dojo;
mod set_trait_eva_angel;
mod set_trait_floating;
mod set_trait_kaijin;
mod set_trait_metal;
mod set_trait_red;
mod set_trait_relic;
mod set_trait_sage;
mod set_trait_starred_alien;
mod set_trait_traitless;
mod set_trait_witch;
mod set_trait_zombie;
mod set_warp_anchor;
mod set_warp_chance;
mod set_warp_distance;
mod set_warp_duration;
mod set_warp_immune;
mod set_warp_resist_pct;
mod set_warp_span;
mod set_warp_timer;
mod set_wave_block;
mod set_wave_chance;
mod set_wave_immune;
mod set_wave_level;
mod set_wave_mini;
mod set_wave_resist_pct;
mod set_weaken_active;
mod set_weaken_active_pct;
mod set_weaken_chance;
mod set_weaken_duration;
mod set_weaken_immune;
mod set_weaken_pct;
mod set_weaken_resist_pct;
mod set_weaken_timer;
mod set_witch_slayer;
mod set_worker_level;
mod set_zkill_hit;
mod set_zombie_killer;
mod sin_deg;
mod slot_conjure_ready;
mod slot_deploy_permitted;
mod slot_occupied;
mod sniper_update;
mod sound_manager;
mod spawn_entity;
mod spawn_warp_tick;
mod special_rules_at;
mod split_row_cells;
mod stage_entry_atk_mag;
mod stage_entry_base_trigger;
mod stage_entry_boss;
mod stage_entry_col10;
mod stage_entry_count;
mod stage_entry_death_gate;
mod stage_entry_enemy_id;
mod stage_entry_is_boss;
mod stage_entry_keep_delay;
mod stage_entry_magnification;
mod stage_entry_respawn_max;
mod stage_entry_respawn_min;
mod stage_entry_row;
mod stage_entry_start_frame;
mod stage_entry_z_max;
mod stage_entry_z_min;
mod stage_has_restriction;
mod stage_not_sealed;
mod start_immune_fx;
mod stat_area_attack;
mod stat_attack_columns;
mod stat_attack_cooldown;
mod stat_attack_count_state;
mod stat_attack_count_total;
mod stat_attack_foreswing;
mod stat_attack_has_abilities;
mod stat_attack_has_ld;
mod stat_attack_ld_anchor;
mod stat_attack_ld_span;
mod stat_attack_only;
mod stat_barrier_breaker_chance;
mod stat_barrier_hitpoints;
mod stat_base_destroyer;
mod stat_behemoth_dodge_chance;
mod stat_behemoth_dodge_duration;
mod stat_behemoth_slayer;
mod stat_boss_wave_immune;
mod stat_colossus_slayer;
mod stat_conjure_unit_id;
mod stat_cooldown;
mod stat_counter_surge;
mod stat_critical_chance;
mod stat_curse_chance;
mod stat_curse_duration;
mod stat_curse_immune;
mod stat_death_surge_anchor;
mod stat_death_surge_chance;
mod stat_death_surge_level;
mod stat_death_surge_span;
mod stat_dodge_chance;
mod stat_dodge_duration;
mod stat_double_bounty;
mod stat_drain_chance;
mod stat_drain_immune;
mod stat_drain_percent;
mod stat_eoc1_cost;
mod stat_eva_killer;
mod stat_explosion_chance;
mod stat_explosion_immune;
mod stat_explosion_spawn_anchor;
mod stat_explosion_spawn_span;
mod stat_freeze_chance;
mod stat_freeze_duration;
mod stat_freeze_immune;
mod stat_has_ability;
mod stat_has_omni_strike;
mod stat_has_shield;
mod stat_has_trait;
mod stat_hitbox_position;
mod stat_hitbox_width;
mod stat_insane_damage;
mod stat_insanely_tough;
mod stat_is_metal;
mod stat_knockback_chance;
mod stat_knockback_immune;
mod stat_knockbacks;
mod stat_massive_damage;
mod stat_metal_killer_percent;
mod stat_mini_surge_flag;
mod stat_mini_wave_flag;
mod stat_resist;
mod stat_sage_slayer;
mod stat_savage_blow_boost;
mod stat_savage_blow_chance;
mod stat_shield_hitpoints;
mod stat_shield_pierce_chance;
mod stat_shield_regen;
mod stat_slow_chance;
mod stat_slow_duration;
mod stat_slow_immune;
mod stat_soul_animation_type;
mod stat_soulstrike;
mod stat_spawn_animation_flag;
mod stat_spawn_animation_type;
mod stat_speed;
mod stat_strengthen_boost;
mod stat_strengthen_threshold;
mod stat_strong_against;
mod stat_surge_chance;
mod stat_surge_immune;
mod stat_surge_level;
mod stat_surge_spawn_anchor;
mod stat_surge_spawn_span;
mod stat_survive;
mod stat_time_before_death;
mod stat_toxic_chance;
mod stat_toxic_damage;
mod stat_toxic_immune;
mod stat_trait_mask;
mod stat_use_gudetama_soul;
mod stat_warp_chance;
mod stat_warp_dist_anchor;
mod stat_warp_dist_span;
mod stat_warp_duration;
mod stat_warp_immune;
mod stat_wave_block;
mod stat_wave_chance;
mod stat_wave_immune;
mod stat_wave_level;
mod stat_weaken_chance;
mod stat_weaken_duration;
mod stat_weaken_immune;
mod stat_weaken_to;
mod stat_witch_killer;
mod stat_zombie_killer;
mod std_map_int_bool_subscript;
mod std_map_int_int_from_list;
mod std_map_int_int_from_list_2;
mod std_map_int_int_insert_range;
mod std_map_int_maanim_subscript;
mod std_map_int_maanim_subscript_2;
mod std_map_int_map_subscript;
mod std_map_int_map_subscript_2;
mod std_map_int_shake_record_subscript;
mod std_map_int_string_subscript;
mod std_map_int_vector_erase;
mod std_map_int_vector_subscript;
mod std_map_string_string_count;
mod std_map_string_string_find_equal;
mod std_stoi;
mod std_string_concat_cstr;
mod std_string_from_cstr;
mod std_vector_int_assign;
mod std_vector_int_push_back;
mod std_vector_int_push_back_2;
mod surge_attack;
mod surge_timing;
mod surge_update;
mod talent_targets_trait;
mod targets_alien;
mod targets_angel;
mod targets_dark;
mod targets_floating;
mod targets_metal;
mod targets_red;
mod targets_zombie;
mod trait_aku;
mod trait_alien;
mod trait_angel;
mod trait_behemoth;
mod trait_colossus;
mod trait_dark;
mod trait_dojo;
mod trait_eva;
mod trait_floating;
mod trait_kaijin;
mod trait_metal;
mod trait_red;
mod trait_relic;
mod trait_sage;
mod trait_starred_alien;
mod trait_traitless;
mod trait_witch;
mod trait_zombie;
mod transform_anchor;
mod transform_point;
mod turn_off_proc_badge;
mod turn_on_proc_badge;
mod unit_meets_restriction;
mod upgrade_worker;
mod validate_map_type;
mod wave_apply_hits;
mod wave_hit_cat_side;
mod wave_hit_enemy_side;
mod wave_update;
mod worker_unlocked;
mod xor_row51_get;
mod xor_row_get;

pub use abs_i32::abs_i32;
pub use add_attacks_remaining::add_attacks_remaining;
pub use add_barrier_fx_frame::add_barrier_fx_frame;
pub use add_behemoth_dodge_timer::add_behemoth_dodge_timer;
pub use add_burrow_count::add_burrow_count;
pub use add_cannon_shot_id::add_cannon_shot_id;
pub use add_castle_anim_frame::add_castle_anim_frame;
pub use add_curse_timer::add_curse_timer;
pub use add_death_timer::add_death_timer;
pub use add_deck_cooldown::add_deck_cooldown;
pub use add_dodge_fx_frame::add_dodge_fx_frame;
pub use add_dodge_timer::add_dodge_timer;
pub use add_drain_pct::add_drain_pct;
pub use add_entity_frame::add_entity_frame;
pub use add_freeze_timer::add_freeze_timer;
pub use add_hit_flash_timer::add_hit_flash_timer;
pub use add_hp::add_hp;
pub use add_kill_count::add_kill_count;
pub use add_medal_progress::add_medal_progress;
pub use add_money::add_money;
pub use add_orb_dodge_timer::add_orb_dodge_timer;
pub use add_pos_x::add_pos_x;
pub use add_revive_count::add_revive_count;
pub use add_revive_timer::add_revive_timer;
pub use add_score_hit_mask::add_score_hit_mask;
pub use add_shield_fx_frame::add_shield_fx_frame;
pub use add_shockwave_counter::add_shockwave_counter;
pub use add_slow_timer::add_slow_timer;
pub use add_warp_timer::add_warp_timer;
pub use add_weaken_timer::add_weaken_timer;
pub use advance_animation_frame::advance_animation_frame;
pub use aku_realm_final_redirect::aku_realm_final_redirect;
pub use app_context::{AppContext, Base, CannonShot, CatStats, Debris, ItemDefinition, WaveRecord, WaveSprite, EnemyStats, Entity, UnitBuy, UNIT_BUY, UNIT_BUY_STRIDE, CAT_STATS, CAT_STATS_FORM_STRIDE, CAT_STATS_UNIT_STRIDE, ENEMY_STATS, ENEMY_STATS_STRIDE, STAGE_ENEMY_COLUMNS, ENTITY_BASE, ENTITY_STRIDE, SIZE, SLOTS_PER_FACTION, FACTION_STRIDE};
pub use asset_stream::{AssetStream, Cell};
pub use atan2_deg::atan2_deg;
pub use attack_ability_fields::ATTACK_ABILITY_FIELDS;
pub use attack_damage_fields::ATTACK_DAMAGE_FIELDS;
pub use attack_dmg_dispatch::attack_dmg_dispatch;
pub use attack_foreswing_fields::ATTACK_FORESWING_FIELDS;
pub use attack_ld_anchor_fields::ATTACK_LD_ANCHOR_FIELDS;
pub use attack_ld_flag_fields::ATTACK_LD_FLAG_FIELDS;
pub use attack_ld_flag_store_fields::ATTACK_LD_FLAG_STORE_FIELDS;
pub use attack_ld_span_fields::ATTACK_LD_SPAN_FIELDS;
pub use attack_proc_dispatch::attack_proc_dispatch;
pub use award_event_points::award_event_points;
pub use base_resists_one_shot::base_resists_one_shot;
pub use base_shake_start::{base_shake_start, BaseShake, ShakeRecord};
pub use base_shake_tick::base_shake_tick;
pub use battle_event_priorities::BATTLE_EVENT_PRIORITIES;
pub use battle_not_finishing::battle_not_finishing;
pub use build_trait_mask::build_trait_mask;
pub use call_rng::call_rng;
pub use can_push_back::can_push_back;
pub use cannon_attack::cannon_attack;
pub use cannon_attack_dispatch::cannon_attack_dispatch;
pub use cannon_fire::cannon_fire;
pub use cannon_hp_mode::cannon_hp_mode;
pub use cannon_makes_wave::cannon_makes_wave;
pub use cannon_reach_x::cannon_reach_x;
pub use cannon_shot_origin_x::cannon_shot_origin_x;
pub use cannon_shot_spacing::CANNON_SHOT_SPACING;
pub use cannon_target_in_range::cannon_target_in_range;
pub use cannon_unlocked::cannon_unlocked;
pub use cat_attack_dispatch::cat_attack_dispatch;
pub use cat_cpu_tick::cat_cpu_tick;
pub use cat_hit_executor::{cat_hit_executor, ExplosionEvent};
pub use cat_update::{cat_update, SurgeEvent};
pub use charagroup_has_unit::{charagroup_has_unit, CharaGroup};
pub use check_collision::check_collision;
pub use compute_attack::compute_attack;
pub use compute_back_bound::compute_back_bound;
pub use compute_event_points::compute_event_points;
pub use compute_hp::compute_hp;
pub use conjurer_on_field::conjurer_on_field;
pub use cos_deg::cos_deg;
pub use count_target_traits::count_target_traits;
pub use counter_surge_update::counter_surge_update;
pub use deck_slot_filled::deck_slot_filled;
pub use deploy_limit_reached::deploy_limit_reached;
pub use deploy_part::deploy_part;
pub use deploy_unit::deploy_unit;
pub use does_target::does_target;
pub use enemy_attack_dispatch::enemy_attack_dispatch;
pub use enemy_hit_executor::enemy_hit_executor;
pub use enemy_schedule_tick::enemy_schedule_tick;
pub use enemy_update::{enemy_update, CounterSurgeEvent};
pub use eoc_chapter_hp_mul::EOC_CHAPTER_HP_MUL;
pub use event_items_count::event_items_count;
pub use event_items_has::{event_items_has, EventItemStore, PointRule, PointRuleDetail, PointRuleTable};
pub use ex_redirect_check_a::ex_redirect_check_a;
pub use ex_redirect_check_b::ex_redirect_check_b;
pub use ex_redirect_check_c::ex_redirect_check_c;
pub use ex_replacement_pending::ex_replacement_pending;
pub use explosion_attack::explosion_attack;
pub use explosion_damage_defaults::EXPLOSION_DAMAGE_DEFAULTS;
pub use explosion_update::explosion_update;
pub use explosion_width_defaults::EXPLOSION_WIDTH_DEFAULTS;
pub use find_built_deck_4star::find_built_deck_4star;
pub use find_point_rule_entry::find_point_rule_entry;
pub use find_score_bonus::{find_score_bonus, ScoredMap};
pub use get_altar_level_cap::get_altar_level_cap;
pub use get_anim_len::get_anim_len;
pub use get_area_attack::get_area_attack;
pub use get_attack_cooldown::get_attack_cooldown;
pub use get_attack_count::get_attack_count;
pub use get_attack_damage::get_attack_damage;
pub use get_attack_end_mode::get_attack_end_mode;
pub use get_attack_foreswing::get_attack_foreswing;
pub use get_attack_interval::get_attack_interval;
pub use get_attack_only::get_attack_only;
pub use get_attacks_remaining::get_attacks_remaining;
pub use get_barrier_breaker_chance::get_barrier_breaker_chance;
pub use get_barrier_fx_active::get_barrier_fx_active;
pub use get_barrier_fx_frame::get_barrier_fx_frame;
pub use get_barrier_hp::get_barrier_hp;
pub use get_barrier_state::get_barrier_state;
pub use get_base_destroyer::get_base_destroyer;
pub use get_base_hp::get_base_hp;
pub use get_base_level::get_base_level;
pub use get_base_max_hp::get_base_max_hp;
pub use get_base_max_hp_div_20::get_base_max_hp_div_20;
pub use get_base_pos_x::get_base_pos_x;
pub use get_base_pos_y::get_base_pos_y;
pub use get_base_shake_offset::get_base_shake_offset;
pub use get_base_soulstrike::get_base_soulstrike;
pub use get_base_upgrade::get_base_upgrade;
pub use get_battle_status::get_battle_status;
pub use get_behemoth_dodge_chance::get_behemoth_dodge_chance;
pub use get_behemoth_dodge_duration::get_behemoth_dodge_duration;
pub use get_behemoth_dodge_timer::get_behemoth_dodge_timer;
pub use get_best_treasure::get_best_treasure;
pub use get_boss_type::get_boss_type;
pub use get_boss_wave_immune::get_boss_wave_immune;
pub use get_built_deck_cannon::{get_built_deck_cannon, BuiltDeckRecord};
pub use get_built_deck_rows::get_built_deck_rows;
pub use get_built_deck_stage_key::get_built_deck_stage_key;
pub use get_burrow_count::get_burrow_count;
pub use get_burrow_distance::get_burrow_distance;
pub use get_burrow_start_x::get_burrow_start_x;
pub use get_button_unit_form::get_button_unit_form;
pub use get_button_unit_id::get_button_unit_id;
pub use get_button_unit_row::get_button_unit_row;
pub use get_cannon_base_damage::get_cannon_base_damage;
pub use get_cannon_blast_hit::get_cannon_blast_hit;
pub use get_cannon_burrowed_permille::get_cannon_burrowed_permille;
pub use get_cannon_charge_orb::get_cannon_charge_orb;
pub use get_cannon_countdown::get_cannon_countdown;
pub use get_cannon_damage::get_cannon_damage;
pub use get_cannon_decor_id::get_cannon_decor_id;
pub use get_cannon_effect::{get_cannon_effect, CannonGrowthStep, CannonPart};
pub use get_cannon_foundation_id::get_cannon_foundation_id;
pub use get_cannon_hit_stamp::get_cannon_hit_stamp;
pub use get_cannon_id::get_cannon_id;
pub use get_cannon_metal_permille::get_cannon_metal_permille;
pub use get_cannon_nonmetal_permille::get_cannon_nonmetal_permille;
pub use get_cannon_nonzombie_permille::get_cannon_nonzombie_permille;
pub use get_cannon_recharge::get_cannon_recharge;
pub use get_cannon_save_value::get_cannon_save_value;
pub use get_cannon_shot_id::get_cannon_shot_id;
pub use get_cannon_strike_width::get_cannon_strike_width;
pub use get_cannon_strike_x::get_cannon_strike_x;
pub use get_cannon_type::get_cannon_type;
pub use get_cannon_unit_id::get_cannon_unit_id;
pub use get_cannon_wall_hp_pct::get_cannon_wall_hp_pct;
pub use get_cannon_wall_lifetime::get_cannon_wall_lifetime;
pub use get_cannon_wall_offset::get_cannon_wall_offset;
pub use get_cannon_zombie_permille::get_cannon_zombie_permille;
pub use get_cash_back_pct::get_cash_back_pct;
pub use get_castle_anim_frame::get_castle_anim_frame;
pub use get_castle_anim_state::get_castle_anim_state;
pub use get_castle_enemy_row::get_castle_enemy_row;
pub use get_castle_id::get_castle_id;
pub use get_castle_row::{get_castle_row, CastleRow};
pub use get_cat_combo_bonus::{get_cat_combo_bonus, ComboStore, NyancomboRecord};
pub use get_cat_combo_values::get_cat_combo_values;
pub use get_cell::get_cell;
pub use get_cleared_count::get_cleared_count;
pub use get_colossus_orb_atk_pct::get_colossus_orb_atk_pct;
pub use get_colossus_orb_def_pct::get_colossus_orb_def_pct;
pub use get_column_count::get_column_count;
pub use get_conjure_unit_id::get_conjure_unit_id;
pub use get_counter_surge::get_counter_surge;
pub use get_counter_surge_once::get_counter_surge_once;
pub use get_counter_surge_pct::get_counter_surge_pct;
pub use get_crit_fx::get_crit_fx;
pub use get_critical_chance::get_critical_chance;
pub use get_current_stage_id::get_current_stage_id;
pub use get_curse_chance::get_curse_chance;
pub use get_curse_duration::get_curse_duration;
pub use get_curse_immune::get_curse_immune;
pub use get_curse_length::get_curse_length;
pub use get_curse_resist_pct::get_curse_resist_pct;
pub use get_curse_timer::get_curse_timer;
pub use get_death_surge_anchor::get_death_surge_anchor;
pub use get_death_surge_level::get_death_surge_level;
pub use get_death_surge_mini::get_death_surge_mini;
pub use get_death_surge_pct::get_death_surge_pct;
pub use get_death_surge_span::get_death_surge_span;
pub use get_death_timer::get_death_timer;
pub use get_deck_cooldown::get_deck_cooldown;
pub use get_deck_cooldown_max::get_deck_cooldown_max;
pub use get_deploy_cost::get_deploy_cost;
pub use get_design_height2::{get_design_height2, ScreenMetrics};
pub use get_dodge_chance::get_dodge_chance;
pub use get_dodge_duration::get_dodge_duration;
pub use get_dodge_fx_frame::get_dodge_fx_frame;
pub use get_dodge_timer::get_dodge_timer;
pub use get_drain_chance::get_drain_chance;
pub use get_drain_immune::get_drain_immune;
pub use get_drain_pct::get_drain_pct;
pub use get_drain_percent::get_drain_percent;
pub use get_effective_deploy_cost::get_effective_deploy_cost;
pub use get_enemy_money_drop::get_enemy_money_drop;
pub use get_entity_base_idx::get_entity_base_idx;
pub use get_entity_button::get_entity_button;
pub use get_entity_frame::get_entity_frame;
pub use get_entity_state::get_entity_state;
pub use get_equipped_orb::get_equipped_orb;
pub use get_equipped_orbs::get_equipped_orbs;
pub use get_ex_option_target::get_ex_option_target;
pub use get_explosion_anchor::get_explosion_anchor;
pub use get_explosion_chance::get_explosion_chance;
pub use get_explosion_immune::get_explosion_immune;
pub use get_explosion_resist_pct::get_explosion_resist_pct;
pub use get_explosion_span::get_explosion_span;
pub use get_first_bounty_pct::get_first_bounty_pct;
pub use get_foundation_part_id::get_foundation_part_id;
pub use get_foundation_part_level::get_foundation_part_level;
pub use get_foundation_part_rec::get_foundation_part_rec;
pub use get_frame_damage::get_frame_damage;
pub use get_freeze_chance::get_freeze_chance;
pub use get_freeze_duration::get_freeze_duration;
pub use get_freeze_immune::get_freeze_immune;
pub use get_freeze_length::get_freeze_length;
pub use get_freeze_resist_pct::get_freeze_resist_pct;
pub use get_freeze_timer::get_freeze_timer;
pub use get_global_map_id::get_global_map_id;
pub use get_gudetama_soul::get_gudetama_soul;
pub use get_hit_flash_timer::get_hit_flash_timer;
pub use get_hitbox_pos::get_hitbox_pos;
pub use get_hp::get_hp;
pub use get_item_count::get_item_count;
pub use get_kb_proc_hit::get_kb_proc_hit;
pub use get_kill_point_base::get_kill_point_base;
pub use get_knockback_chance::get_knockback_chance;
pub use get_knockback_immune::get_knockback_immune;
pub use get_knockback_resist_pct::get_knockback_resist_pct;
pub use get_knockbacks::get_knockbacks;
pub use get_ld_anchor::get_ld_anchor;
pub use get_ld_span::get_ld_span;
pub use get_listed_item_count::get_listed_item_count;
pub use get_map_cost_multiplier::get_map_cost_multiplier;
pub use get_map_count::get_map_count;
pub use get_map_index::get_map_index;
pub use get_map_rules::get_map_rules;
pub use get_map_type::get_map_type;
pub use get_max_hp::get_max_hp;
pub use get_max_money::get_max_money;
pub use get_medal_progress::get_medal_progress;
pub use get_metal_killer_fx::get_metal_killer_fx;
pub use get_metal_killer_pct::get_metal_killer_pct;
pub use get_mini_surge::get_mini_surge;
pub use get_money::get_money;
pub use get_money_increment::get_money_increment;
pub use get_no_revive::get_no_revive;
pub use get_occupant::get_occupant;
pub use get_orb_dodge_chance::get_orb_dodge_chance;
pub use get_orb_dodge_duration::get_orb_dodge_duration;
pub use get_orb_dodge_timer::get_orb_dodge_timer;
pub use get_orb_value_max::{get_orb_value_max, OrbDef, OrbStore};
pub use get_orb_value_sum::get_orb_value_sum;
pub use get_orb_value_vs_trait::get_orb_value_vs_trait;
pub use get_paid_cost::get_paid_cost;
pub use get_point_rule::get_point_rule;
pub use get_point_rule_type::get_point_rule_type;
pub use get_pos_x::get_pos_x;
pub use get_pos_y::get_pos_y;
pub use get_powerup::get_powerup;
pub use get_powerup_available::get_powerup_available;
pub use get_preset_foundation_part::get_preset_foundation_part;
pub use get_preset_style_part::get_preset_style_part;
pub use get_prev_curse_timer::get_prev_curse_timer;
pub use get_prev_freeze_timer::get_prev_freeze_timer;
pub use get_prev_slow_timer::get_prev_slow_timer;
pub use get_prev_weaken_timer::get_prev_weaken_timer;
pub use get_proc_badge::get_proc_badge;
pub use get_resist_part_rec::get_resist_part_rec;
pub use get_revive_count::get_revive_count;
pub use get_revive_hp::get_revive_hp;
pub use get_revive_time::get_revive_time;
pub use get_revive_timer::get_revive_timer;
pub use get_sage_kb_resist_pct::get_sage_kb_resist_pct;
pub use get_savage_blow_boost::get_savage_blow_boost;
pub use get_savage_blow_chance::get_savage_blow_chance;
pub use get_savage_blow_fx::get_savage_blow_fx;
pub use get_scene_id::get_scene_id;
pub use get_score_bonus::get_score_bonus;
pub use get_score_hit_mask::get_score_hit_mask;
pub use get_score_time_limit::get_score_time_limit;
pub use get_score_value::get_score_value;
pub use get_setting::get_setting;
pub use get_shield_fx::get_shield_fx;
pub use get_shield_fx_frame::get_shield_fx_frame;
pub use get_shield_hp::get_shield_hp;
pub use get_shield_max::get_shield_max;
pub use get_shield_pierce_chance::get_shield_pierce_chance;
pub use get_shield_regen::get_shield_regen;
pub use get_shield_state::get_shield_state;
pub use get_shockwave_counter::get_shockwave_counter;
pub use get_slot_unit_id::get_slot_unit_id;
pub use get_slow_chance::get_slow_chance;
pub use get_slow_duration::get_slow_duration;
pub use get_slow_immune::get_slow_immune;
pub use get_slow_length::get_slow_length;
pub use get_slow_resist_pct::get_slow_resist_pct;
pub use get_slow_timer::get_slow_timer;
pub use get_soul_anim_type::get_soul_anim_type;
pub use get_soulstrike::get_soulstrike;
pub use get_spawn_anim_flag::get_spawn_anim_flag;
pub use get_spawn_anim_type::get_spawn_anim_type;
pub use get_spawn_serial::get_spawn_serial;
pub use get_special_rule::get_special_rule;
pub use get_special_rule_params::get_special_rule_params;
pub use get_speed::get_speed;
pub use get_stage_count::get_stage_count;
pub use get_stage_index::get_stage_index;
pub use get_stage_record::get_stage_record;
pub use get_stage_set_size::{get_stage_set_size, MapData};
pub use get_stages_cleared::get_stages_cleared;
pub use get_standing_range::get_standing_range;
pub use get_star_level::get_star_level;
pub use get_star_multiplier::get_star_multiplier;
pub use get_stat_range::get_stat_range;
pub use get_status_bits::get_status_bits;
pub use get_strengthen_boost::get_strengthen_boost;
pub use get_strengthen_threshold::get_strengthen_threshold;
pub use get_style_part_id::get_style_part_id;
pub use get_style_part_level::get_style_part_level;
pub use get_surge_anchor::get_surge_anchor;
pub use get_surge_chance::get_surge_chance;
pub use get_surge_immune::get_surge_immune;
pub use get_surge_level::get_surge_level;
pub use get_surge_resist_pct::get_surge_resist_pct;
pub use get_surge_span::get_surge_span;
pub use get_talent_icon_state::get_talent_icon_state;
pub use get_talent_value::get_talent_value;
pub use get_tech_level::get_tech_level;
pub use get_took_damage::get_took_damage;
pub use get_total_damage_taken::get_total_damage_taken;
pub use get_toxic_chance::get_toxic_chance;
pub use get_toxic_damage::get_toxic_damage;
pub use get_toxic_fx::get_toxic_fx;
pub use get_toxic_immune::get_toxic_immune;
pub use get_toxic_resist_pct::get_toxic_resist_pct;
pub use get_trait_dojo::get_trait_dojo;
pub use get_trait_kaijin::get_trait_kaijin;
pub use get_treasure_capped::get_treasure_capped;
pub use get_treasure_uncapped::get_treasure_uncapped;
pub use get_treasure_value::{get_treasure_value, TreasureGroup, TreasureStore};
pub use get_unit_anim::get_unit_anim;
pub use get_unit_form::get_unit_form;
pub use get_unit_max_level::get_unit_max_level;
pub use get_unit_model::get_unit_model;
pub use get_unit_name::get_unit_name;
pub use get_unit_rarity::get_unit_rarity;
pub use get_unit_recharge::get_unit_recharge;
pub use get_warp_anchor::get_warp_anchor;
pub use get_warp_chance::get_warp_chance;
pub use get_warp_distance::get_warp_distance;
pub use get_warp_duration::get_warp_duration;
pub use get_warp_immune::get_warp_immune;
pub use get_warp_resist_pct::get_warp_resist_pct;
pub use get_warp_span::get_warp_span;
pub use get_warp_timer::get_warp_timer;
pub use get_wave_block::get_wave_block;
pub use get_wave_chance::get_wave_chance;
pub use get_wave_hit_faction::get_wave_hit_faction;
pub use get_wave_immune::get_wave_immune;
pub use get_wave_level::get_wave_level;
pub use get_wave_mini::get_wave_mini;
pub use get_wave_resist_pct::get_wave_resist_pct;
pub use get_weaken_active::get_weaken_active;
pub use get_weaken_active_pct::get_weaken_active_pct;
pub use get_weaken_chance::get_weaken_chance;
pub use get_weaken_duration::get_weaken_duration;
pub use get_weaken_immune::get_weaken_immune;
pub use get_weaken_pct::get_weaken_pct;
pub use get_weaken_resist_pct::get_weaken_resist_pct;
pub use get_weaken_timer::get_weaken_timer;
pub use get_worker_level::get_worker_level;
pub use get_worker_upgrade_cost::get_worker_upgrade_cost;
pub use get_worker_upgrade_level::get_worker_upgrade_level;
pub use get_zkill_hit::get_zkill_hit;
pub use has_attack_abilities::has_attack_abilities;
pub use has_barrier_breaker_chance::has_barrier_breaker_chance;
pub use has_base_curse_chance::has_base_curse_chance;
pub use has_base_freeze_chance::has_base_freeze_chance;
pub use has_base_slow_chance::has_base_slow_chance;
pub use has_behemoth_slayer::has_behemoth_slayer;
pub use has_built_deck::has_built_deck;
pub use has_cannon_ready_fx::has_cannon_ready_fx;
pub use has_cannon_recoil::has_cannon_recoil;
pub use has_castle_enemy::has_castle_enemy;
pub use has_colossus_slayer::has_colossus_slayer;
pub use has_conjure_deck_slot::has_conjure_deck_slot;
pub use has_critical_chance::has_critical_chance;
pub use has_curse_chance::has_curse_chance;
pub use has_double_bounty::has_double_bounty;
pub use has_drain_chance::has_drain_chance;
pub use has_eva_killer::has_eva_killer;
pub use has_fixed_lineup::{has_fixed_lineup, FixedLineupRow, FixedLineupStore, FixedLineupUnit};
pub use has_freeze_chance::has_freeze_chance;
pub use has_insane_damage::has_insane_damage;
pub use has_insanely_tough::has_insanely_tough;
pub use has_knockback_chance::has_knockback_chance;
pub use has_massive_damage::has_massive_damage;
pub use has_orb::has_orb;
pub use has_resist::has_resist;
pub use has_sage_slayer::has_sage_slayer;
pub use has_savage_blow_chance::has_savage_blow_chance;
pub use has_shield_pierce_chance::has_shield_pierce_chance;
pub use has_slow_chance::has_slow_chance;
pub use has_strong_against::has_strong_against;
pub use has_talent::has_talent;
pub use has_toxic_chance::has_toxic_chance;
pub use has_warp_chance::has_warp_chance;
pub use has_weaken_chance::has_weaken_chance;
pub use has_witch_slayer::has_witch_slayer;
pub use has_zombie_killer::has_zombie_killer;
pub use imgcut_get_cut_count::imgcut_get_cut_count;
pub use imgcut_get_height::imgcut_get_height;
pub use imgcut_get_sprite_cut::imgcut_get_sprite_cut;
pub use imgcut_get_width::imgcut_get_width;
pub use imgcut_load::{imgcut_load, Imgcut, CUT_CELLS};
pub use invasion_available::invasion_available;
pub use invasion_z_available::invasion_z_available;
pub use is_aku::is_aku;
pub use is_alien::is_alien;
pub use is_angel::is_angel;
pub use is_attack_long_range::is_attack_long_range;
pub use is_behemoth::is_behemoth;
pub use is_boss::is_boss;
pub use is_boss_guarding_base::is_boss_guarding_base;
pub use is_cannon_target::is_cannon_target;
pub use is_colossus::is_colossus;
pub use is_dark::is_dark;
pub use is_deploy_blocked::is_deploy_blocked;
pub use is_eva_angel::is_eva_angel;
pub use is_ex_map_68::is_ex_map_68;
pub use is_ex_option_target::is_ex_option_target;
pub use is_floating::is_floating;
pub use is_invasion_stage::is_invasion_stage;
pub use is_map_cleared::is_map_cleared;
pub use is_metal::is_metal;
pub use is_outbreak_stage::is_outbreak_stage;
pub use is_red::is_red;
pub use is_relic::is_relic;
pub use is_sage::is_sage;
pub use is_score_stage::is_score_stage;
pub use is_scored_stage::is_scored_stage;
pub use is_touchable::is_touchable;
pub use is_touchable_thunk::is_touchable_thunk;
pub use is_trait_targeted_talent::is_trait_targeted_talent;
pub use is_traitless::is_traitless;
pub use is_witch::is_witch;
pub use is_z_invasion_stage::is_z_invasion_stage;
pub use is_zombie::is_zombie;
pub use keep_in_bound::keep_in_bound;
pub use knockback_y_arc::KNOCKBACK_Y_ARC;
pub use labyrinth_active::labyrinth_active;
pub use latch_battle_event::{latch_battle_event, BattleEventLatch};
pub use level_cell_base::level_cell_base;
pub use level_cell_plus::level_cell_plus;
pub use load_cat_combat_csv::load_cat_combat_csv;
pub use load_cat_data_files::load_cat_data_files;
pub use load_enemy_castle_csv::load_enemy_castle_csv;
pub use load_enemy_combat_csv::load_enemy_combat_csv;
pub use load_stage_csv::load_stage_csv;
pub use maanim_animate::maanim_animate;
pub use maanim_execute::maanim_execute;
pub use maanim_get_max_keyframe::maanim_get_max_keyframe;
pub use maanim_initialize::maanim_initialize;
pub use maanim_load::{maanim_load, Maanim, MaanimTrack, KEYFRAME_CELLS, TRACK_HEADER_CELLS};
pub use mamodel_get_anchor::mamodel_get_anchor;
pub use mamodel_get_anchor_part::mamodel_get_anchor_part;
pub use mamodel_get_anchor_x::mamodel_get_anchor_x;
pub use mamodel_get_anchor_y::mamodel_get_anchor_y;
pub use mamodel_load::{mamodel_load, Mamodel, MamodelAnchor, MamodelPart, PART_STRIDE};
pub use map_type_as_index::map_type_as_index;
pub use map_type_base_id::map_type_base_id;
pub use matrix_rotate::matrix_rotate;
pub use matrix_set_translation::matrix_set_translation;
pub use matrix_translate::matrix_translate;
pub use max_i32::max_i32;
pub use min_i32::min_i32;
pub use no_more_attacks::no_more_attacks;
pub use obf_value_read::obf_value_read;
pub use obf_value_read_2::obf_value_read_2;
pub use obfuscate_value::obfuscate_value;
pub use orb_deploy_condition::orb_deploy_condition;
pub use orb_deploy_condition_slot::orb_deploy_condition_slot;
pub use parse_stage_enemy_row::parse_stage_enemy_row;
pub use pending_strike_hit::pending_strike_hit;
pub use play_sound::play_sound;
pub use play_sound_in_battle::play_sound_in_battle;
pub use point_band_lookup::point_band_lookup;
pub use proc_badge_fields::PROC_BADGE_FIELDS;
pub use proc_update::{proc_update, BattleEffects};
pub use read_asset_stream_line::read_asset_stream_line;
pub use read_cell_stream::read_cell_stream;
pub use read_csv_cell::read_csv_cell;
pub use read_csv_row::read_csv_row;
pub use read_flag::read_flag;
pub use read_stream_row::read_stream_row;
pub use read_tsv_row::read_tsv_row;
pub use recoil_y_arc::RECOIL_Y_ARC;
pub use recount_deploy_rarities::recount_deploy_rarities;
pub use rng::rng;
pub use roll_procs::roll_procs;
pub use scored_map_pays_money::scored_map_pays_money;
pub use set_area_attack::set_area_attack;
pub use set_attack_abilities::set_attack_abilities;
pub use set_attack_cooldown::set_attack_cooldown;
pub use set_attack_damage::set_attack_damage;
pub use set_attack_end_mode::set_attack_end_mode;
pub use set_attack_foreswing::set_attack_foreswing;
pub use set_attack_interval::set_attack_interval;
pub use set_attack_only::set_attack_only;
pub use set_attacks_remaining::set_attacks_remaining;
pub use set_barrier_breaker_chance::set_barrier_breaker_chance;
pub use set_barrier_fx_active::set_barrier_fx_active;
pub use set_barrier_fx_frame::set_barrier_fx_frame;
pub use set_barrier_hp::set_barrier_hp;
pub use set_barrier_state::set_barrier_state;
pub use set_base_curse_chance::set_base_curse_chance;
pub use set_base_curse_duration::set_base_curse_duration;
pub use set_base_destroyer::set_base_destroyer;
pub use set_base_entity_frame::set_base_entity_frame;
pub use set_base_freeze_chance::set_base_freeze_chance;
pub use set_base_freeze_duration::set_base_freeze_duration;
pub use set_base_guard_notice::set_base_guard_notice;
pub use set_base_hitbox_pos::set_base_hitbox_pos;
pub use set_base_hitbox_width::set_base_hitbox_width;
pub use set_base_hp::set_base_hp;
pub use set_base_level::set_base_level;
pub use set_base_max_hp::set_base_max_hp;
pub use set_base_occupant::set_base_occupant;
pub use set_base_pos_x::set_base_pos_x;
pub use set_base_pos_y::set_base_pos_y;
pub use set_base_slow_chance::set_base_slow_chance;
pub use set_base_slow_duration::set_base_slow_duration;
pub use set_base_soulstrike::set_base_soulstrike;
pub use set_base_state::set_base_state;
pub use set_behemoth_dodge_chance::set_behemoth_dodge_chance;
pub use set_behemoth_dodge_duration::set_behemoth_dodge_duration;
pub use set_behemoth_dodge_timer::set_behemoth_dodge_timer;
pub use set_behemoth_slayer::set_behemoth_slayer;
pub use set_boss_type::set_boss_type;
pub use set_boss_wave_immune::set_boss_wave_immune;
pub use set_burrow_count::set_burrow_count;
pub use set_burrow_distance::set_burrow_distance;
pub use set_burrow_start_x::set_burrow_start_x;
pub use set_cannon_base_damage::set_cannon_base_damage;
pub use set_cannon_blast_hit::set_cannon_blast_hit;
pub use set_cannon_burrowed_permille::set_cannon_burrowed_permille;
pub use set_cannon_charge_orb::set_cannon_charge_orb;
pub use set_cannon_countdown::set_cannon_countdown;
pub use set_cannon_damage::set_cannon_damage;
pub use set_cannon_hit_stamp::set_cannon_hit_stamp;
pub use set_cannon_hp_mode::set_cannon_hp_mode;
pub use set_cannon_makes_wave::set_cannon_makes_wave;
pub use set_cannon_metal_permille::set_cannon_metal_permille;
pub use set_cannon_nonmetal_permille::set_cannon_nonmetal_permille;
pub use set_cannon_nonzombie_permille::set_cannon_nonzombie_permille;
pub use set_cannon_parts::set_cannon_parts;
pub use set_cannon_ready_fx::set_cannon_ready_fx;
pub use set_cannon_recharge::set_cannon_recharge;
pub use set_cannon_recoil::set_cannon_recoil;
pub use set_cannon_shot_id::set_cannon_shot_id;
pub use set_cannon_strike_width::set_cannon_strike_width;
pub use set_cannon_strike_x::set_cannon_strike_x;
pub use set_cannon_type::set_cannon_type;
pub use set_cannon_unit_id::set_cannon_unit_id;
pub use set_cannon_wall_hp_pct::set_cannon_wall_hp_pct;
pub use set_cannon_wall_lifetime::set_cannon_wall_lifetime;
pub use set_cannon_wall_offset::set_cannon_wall_offset;
pub use set_cannon_zombie_permille::set_cannon_zombie_permille;
pub use set_cash_back_pct::set_cash_back_pct;
pub use set_castle_anim_frame::set_castle_anim_frame;
pub use set_castle_anim_state::set_castle_anim_state;
pub use set_colossus_orb_pcts::set_colossus_orb_pcts;
pub use set_colossus_slayer::set_colossus_slayer;
pub use set_conjure_deck_slot::set_conjure_deck_slot;
pub use set_conjure_unit_id::set_conjure_unit_id;
pub use set_counter_surge::set_counter_surge;
pub use set_counter_surge_once::set_counter_surge_once;
pub use set_counter_surge_pct::set_counter_surge_pct;
pub use set_crit_fx::set_crit_fx;
pub use set_critical_chance::set_critical_chance;
pub use set_curse_chance::set_curse_chance;
pub use set_curse_duration::set_curse_duration;
pub use set_curse_immune::set_curse_immune;
pub use set_curse_length::set_curse_length;
pub use set_curse_resist_pct::set_curse_resist_pct;
pub use set_curse_timer::set_curse_timer;
pub use set_death_surge_anchor::set_death_surge_anchor;
pub use set_death_surge_chance::set_death_surge_chance;
pub use set_death_surge_level::set_death_surge_level;
pub use set_death_surge_mini::set_death_surge_mini;
pub use set_death_surge_pct::set_death_surge_pct;
pub use set_death_surge_span::set_death_surge_span;
pub use set_death_timer::set_death_timer;
pub use set_deck_cooldown::set_deck_cooldown;
pub use set_deck_cooldown_max::set_deck_cooldown_max;
pub use set_dodge_chance::set_dodge_chance;
pub use set_dodge_duration::set_dodge_duration;
pub use set_dodge_fx_frame::set_dodge_fx_frame;
pub use set_dodge_timer::set_dodge_timer;
pub use set_double_bounty::set_double_bounty;
pub use set_drain_chance::set_drain_chance;
pub use set_drain_immune::set_drain_immune;
pub use set_drain_pct::set_drain_pct;
pub use set_drain_percent::set_drain_percent;
pub use set_entity_frame::set_entity_frame;
pub use set_entity_state::set_entity_state;
pub use set_eva_killer::set_eva_killer;
pub use set_explosion_anchor::set_explosion_anchor;
pub use set_explosion_chance::set_explosion_chance;
pub use set_explosion_immune::set_explosion_immune;
pub use set_explosion_resist_pct::set_explosion_resist_pct;
pub use set_explosion_span::set_explosion_span;
pub use set_first_bounty_pct::set_first_bounty_pct;
pub use set_frame_damage::set_frame_damage;
pub use set_freeze_chance::set_freeze_chance;
pub use set_freeze_duration::set_freeze_duration;
pub use set_freeze_immune::set_freeze_immune;
pub use set_freeze_length::set_freeze_length;
pub use set_freeze_resist_pct::set_freeze_resist_pct;
pub use set_freeze_timer::set_freeze_timer;
pub use set_gudetama_soul::set_gudetama_soul;
pub use set_hit_flash_timer::set_hit_flash_timer;
pub use set_hitbox_pos::set_hitbox_pos;
pub use set_hitbox_width::set_hitbox_width;
pub use set_hp::set_hp;
pub use set_insane_damage::set_insane_damage;
pub use set_insanely_tough::set_insanely_tough;
pub use set_kb_proc_hit::set_kb_proc_hit;
pub use set_kill_count::set_kill_count;
pub use set_knockback_chance::set_knockback_chance;
pub use set_knockback_immune::set_knockback_immune;
pub use set_knockback_resist_pct::set_knockback_resist_pct;
pub use set_knockbacks::set_knockbacks;
pub use set_ld_anchor::set_ld_anchor;
pub use set_ld_flag::set_ld_flag;
pub use set_ld_span::set_ld_span;
pub use set_massive_damage::set_massive_damage;
pub use set_max_hp::set_max_hp;
pub use set_metal::set_metal;
pub use set_metal_killer_fx::set_metal_killer_fx;
pub use set_metal_killer_pct::set_metal_killer_pct;
pub use set_mini_surge::set_mini_surge;
pub use set_money::set_money;
pub use set_no_revive::set_no_revive;
pub use set_occupant::set_occupant;
pub use set_orb_dodge_chance::set_orb_dodge_chance;
pub use set_orb_dodge_duration::set_orb_dodge_duration;
pub use set_orb_dodge_timer::set_orb_dodge_timer;
pub use set_paid_cost::set_paid_cost;
pub use set_pos_x::set_pos_x;
pub use set_pos_y::set_pos_y;
pub use set_powerup::set_powerup;
pub use set_prev_curse_timer::set_prev_curse_timer;
pub use set_prev_freeze_timer::set_prev_freeze_timer;
pub use set_prev_slow_timer::set_prev_slow_timer;
pub use set_prev_weaken_timer::set_prev_weaken_timer;
pub use set_proc_badge::set_proc_badge;
pub use set_resist::set_resist;
pub use set_revive_count::set_revive_count;
pub use set_revive_hp::set_revive_hp;
pub use set_revive_time::set_revive_time;
pub use set_revive_timer::set_revive_timer;
pub use set_sage_kb_resist_pct::set_sage_kb_resist_pct;
pub use set_sage_slayer::set_sage_slayer;
pub use set_savage_blow_boost::set_savage_blow_boost;
pub use set_savage_blow_chance::set_savage_blow_chance;
pub use set_savage_blow_fx::set_savage_blow_fx;
pub use set_score_hit_mask::set_score_hit_mask;
pub use set_score_value::set_score_value;
pub use set_shield_fx::set_shield_fx;
pub use set_shield_fx_frame::set_shield_fx_frame;
pub use set_shield_hp::set_shield_hp;
pub use set_shield_max::set_shield_max;
pub use set_shield_pierce_chance::set_shield_pierce_chance;
pub use set_shield_regen::set_shield_regen;
pub use set_shield_state::set_shield_state;
pub use set_shockwave_counter::set_shockwave_counter;
pub use set_slow_chance::set_slow_chance;
pub use set_slow_duration::set_slow_duration;
pub use set_slow_immune::set_slow_immune;
pub use set_slow_length::set_slow_length;
pub use set_slow_resist_pct::set_slow_resist_pct;
pub use set_slow_timer::set_slow_timer;
pub use set_soul_anim_type::set_soul_anim_type;
pub use set_soulstrike::set_soulstrike;
pub use set_spawn_anim_flag::set_spawn_anim_flag;
pub use set_spawn_anim_type::set_spawn_anim_type;
pub use set_spawn_serial::set_spawn_serial;
pub use set_speed::set_speed;
pub use set_stage_entry_enemy::set_stage_entry_enemy;
pub use set_standing_range::set_standing_range;
pub use set_strengthen_boost::set_strengthen_boost;
pub use set_strengthen_threshold::set_strengthen_threshold;
pub use set_strong_against::set_strong_against;
pub use set_surge_anchor::set_surge_anchor;
pub use set_surge_chance::set_surge_chance;
pub use set_surge_immune::set_surge_immune;
pub use set_surge_level::set_surge_level;
pub use set_surge_resist_pct::set_surge_resist_pct;
pub use set_surge_span::set_surge_span;
pub use set_survive_chance::set_survive_chance;
pub use set_total_damage_taken::set_total_damage_taken;
pub use set_toxic_chance::set_toxic_chance;
pub use set_toxic_damage::set_toxic_damage;
pub use set_toxic_fx::set_toxic_fx;
pub use set_toxic_immune::set_toxic_immune;
pub use set_toxic_resist_pct::set_toxic_resist_pct;
pub use set_trait_aku::set_trait_aku;
pub use set_trait_alien::set_trait_alien;
pub use set_trait_angel::set_trait_angel;
pub use set_trait_behemoth::set_trait_behemoth;
pub use set_trait_colossus::set_trait_colossus;
pub use set_trait_dark::set_trait_dark;
pub use set_trait_dojo::set_trait_dojo;
pub use set_trait_eva_angel::set_trait_eva_angel;
pub use set_trait_floating::set_trait_floating;
pub use set_trait_kaijin::set_trait_kaijin;
pub use set_trait_metal::set_trait_metal;
pub use set_trait_red::set_trait_red;
pub use set_trait_relic::set_trait_relic;
pub use set_trait_sage::set_trait_sage;
pub use set_trait_starred_alien::set_trait_starred_alien;
pub use set_trait_traitless::set_trait_traitless;
pub use set_trait_witch::set_trait_witch;
pub use set_trait_zombie::set_trait_zombie;
pub use set_warp_anchor::set_warp_anchor;
pub use set_warp_chance::set_warp_chance;
pub use set_warp_distance::set_warp_distance;
pub use set_warp_duration::set_warp_duration;
pub use set_warp_immune::set_warp_immune;
pub use set_warp_resist_pct::set_warp_resist_pct;
pub use set_warp_span::set_warp_span;
pub use set_warp_timer::set_warp_timer;
pub use set_wave_block::set_wave_block;
pub use set_wave_chance::set_wave_chance;
pub use set_wave_immune::set_wave_immune;
pub use set_wave_level::set_wave_level;
pub use set_wave_mini::set_wave_mini;
pub use set_wave_resist_pct::set_wave_resist_pct;
pub use set_weaken_active::set_weaken_active;
pub use set_weaken_active_pct::set_weaken_active_pct;
pub use set_weaken_chance::set_weaken_chance;
pub use set_weaken_duration::set_weaken_duration;
pub use set_weaken_immune::set_weaken_immune;
pub use set_weaken_pct::set_weaken_pct;
pub use set_weaken_resist_pct::set_weaken_resist_pct;
pub use set_weaken_timer::set_weaken_timer;
pub use set_witch_slayer::set_witch_slayer;
pub use set_worker_level::set_worker_level;
pub use set_zkill_hit::set_zkill_hit;
pub use set_zombie_killer::set_zombie_killer;
pub use sin_deg::sin_deg;
pub use slot_conjure_ready::slot_conjure_ready;
pub use slot_deploy_permitted::slot_deploy_permitted;
pub use slot_occupied::slot_occupied;
pub use sniper_update::sniper_update;
pub use sound_manager::{sound_manager, SoundManager};
pub use spawn_entity::spawn_entity;
pub use spawn_warp_tick::spawn_warp_tick;
pub use special_rules_at::{special_rules_at, MapRules, SpecialRuleStore};
pub use split_row_cells::split_row_cells;
pub use stage_entry_atk_mag::stage_entry_atk_mag;
pub use stage_entry_base_trigger::stage_entry_base_trigger;
pub use stage_entry_boss::stage_entry_boss;
pub use stage_entry_col10::stage_entry_col10;
pub use stage_entry_count::stage_entry_count;
pub use stage_entry_death_gate::stage_entry_death_gate;
pub use stage_entry_enemy_id::stage_entry_enemy_id;
pub use stage_entry_is_boss::stage_entry_is_boss;
pub use stage_entry_keep_delay::stage_entry_keep_delay;
pub use stage_entry_magnification::stage_entry_magnification;
pub use stage_entry_respawn_max::stage_entry_respawn_max;
pub use stage_entry_respawn_min::stage_entry_respawn_min;
pub use stage_entry_row::stage_entry_row;
pub use stage_entry_start_frame::stage_entry_start_frame;
pub use stage_entry_z_max::stage_entry_z_max;
pub use stage_entry_z_min::stage_entry_z_min;
pub use stage_has_restriction::{stage_has_restriction, StageRestriction};
pub use stage_not_sealed::stage_not_sealed;
pub use start_immune_fx::start_immune_fx;
pub use stat_area_attack::stat_area_attack;
pub use stat_attack_columns::STAT_ATTACK_COLUMNS;
pub use stat_attack_cooldown::stat_attack_cooldown;
pub use stat_attack_count_state::stat_attack_count_state;
pub use stat_attack_count_total::stat_attack_count_total;
pub use stat_attack_foreswing::stat_attack_foreswing;
pub use stat_attack_has_abilities::stat_attack_has_abilities;
pub use stat_attack_has_ld::stat_attack_has_ld;
pub use stat_attack_ld_anchor::stat_attack_ld_anchor;
pub use stat_attack_ld_span::stat_attack_ld_span;
pub use stat_attack_only::stat_attack_only;
pub use stat_barrier_breaker_chance::stat_barrier_breaker_chance;
pub use stat_barrier_hitpoints::stat_barrier_hitpoints;
pub use stat_base_destroyer::stat_base_destroyer;
pub use stat_behemoth_dodge_chance::stat_behemoth_dodge_chance;
pub use stat_behemoth_dodge_duration::stat_behemoth_dodge_duration;
pub use stat_behemoth_slayer::stat_behemoth_slayer;
pub use stat_boss_wave_immune::stat_boss_wave_immune;
pub use stat_colossus_slayer::stat_colossus_slayer;
pub use stat_conjure_unit_id::stat_conjure_unit_id;
pub use stat_cooldown::stat_cooldown;
pub use stat_counter_surge::stat_counter_surge;
pub use stat_critical_chance::stat_critical_chance;
pub use stat_curse_chance::stat_curse_chance;
pub use stat_curse_duration::stat_curse_duration;
pub use stat_curse_immune::stat_curse_immune;
pub use stat_death_surge_anchor::stat_death_surge_anchor;
pub use stat_death_surge_chance::stat_death_surge_chance;
pub use stat_death_surge_level::stat_death_surge_level;
pub use stat_death_surge_span::stat_death_surge_span;
pub use stat_dodge_chance::stat_dodge_chance;
pub use stat_dodge_duration::stat_dodge_duration;
pub use stat_double_bounty::stat_double_bounty;
pub use stat_drain_chance::stat_drain_chance;
pub use stat_drain_immune::stat_drain_immune;
pub use stat_drain_percent::stat_drain_percent;
pub use stat_eoc1_cost::stat_eoc1_cost;
pub use stat_eva_killer::stat_eva_killer;
pub use stat_explosion_chance::stat_explosion_chance;
pub use stat_explosion_immune::stat_explosion_immune;
pub use stat_explosion_spawn_anchor::stat_explosion_spawn_anchor;
pub use stat_explosion_spawn_span::stat_explosion_spawn_span;
pub use stat_freeze_chance::stat_freeze_chance;
pub use stat_freeze_duration::stat_freeze_duration;
pub use stat_freeze_immune::stat_freeze_immune;
pub use stat_has_ability::stat_has_ability;
pub use stat_has_omni_strike::stat_has_omni_strike;
pub use stat_has_shield::stat_has_shield;
pub use stat_has_trait::stat_has_trait;
pub use stat_hitbox_position::stat_hitbox_position;
pub use stat_hitbox_width::stat_hitbox_width;
pub use stat_insane_damage::stat_insane_damage;
pub use stat_insanely_tough::stat_insanely_tough;
pub use stat_is_metal::stat_is_metal;
pub use stat_knockback_chance::stat_knockback_chance;
pub use stat_knockback_immune::stat_knockback_immune;
pub use stat_knockbacks::stat_knockbacks;
pub use stat_massive_damage::stat_massive_damage;
pub use stat_metal_killer_percent::stat_metal_killer_percent;
pub use stat_mini_surge_flag::stat_mini_surge_flag;
pub use stat_mini_wave_flag::stat_mini_wave_flag;
pub use stat_resist::stat_resist;
pub use stat_sage_slayer::stat_sage_slayer;
pub use stat_savage_blow_boost::stat_savage_blow_boost;
pub use stat_savage_blow_chance::stat_savage_blow_chance;
pub use stat_shield_hitpoints::stat_shield_hitpoints;
pub use stat_shield_pierce_chance::stat_shield_pierce_chance;
pub use stat_shield_regen::stat_shield_regen;
pub use stat_slow_chance::stat_slow_chance;
pub use stat_slow_duration::stat_slow_duration;
pub use stat_slow_immune::stat_slow_immune;
pub use stat_soul_animation_type::stat_soul_animation_type;
pub use stat_soulstrike::stat_soulstrike;
pub use stat_spawn_animation_flag::stat_spawn_animation_flag;
pub use stat_spawn_animation_type::stat_spawn_animation_type;
pub use stat_speed::stat_speed;
pub use stat_strengthen_boost::stat_strengthen_boost;
pub use stat_strengthen_threshold::stat_strengthen_threshold;
pub use stat_strong_against::stat_strong_against;
pub use stat_surge_chance::stat_surge_chance;
pub use stat_surge_immune::stat_surge_immune;
pub use stat_surge_level::stat_surge_level;
pub use stat_surge_spawn_anchor::stat_surge_spawn_anchor;
pub use stat_surge_spawn_span::stat_surge_spawn_span;
pub use stat_survive::stat_survive;
pub use stat_time_before_death::stat_time_before_death;
pub use stat_toxic_chance::stat_toxic_chance;
pub use stat_toxic_damage::stat_toxic_damage;
pub use stat_toxic_immune::stat_toxic_immune;
pub use stat_trait_mask::stat_trait_mask;
pub use stat_use_gudetama_soul::stat_use_gudetama_soul;
pub use stat_warp_chance::stat_warp_chance;
pub use stat_warp_dist_anchor::stat_warp_dist_anchor;
pub use stat_warp_dist_span::stat_warp_dist_span;
pub use stat_warp_duration::stat_warp_duration;
pub use stat_warp_immune::stat_warp_immune;
pub use stat_wave_block::stat_wave_block;
pub use stat_wave_chance::stat_wave_chance;
pub use stat_wave_immune::stat_wave_immune;
pub use stat_wave_level::stat_wave_level;
pub use stat_weaken_chance::stat_weaken_chance;
pub use stat_weaken_duration::stat_weaken_duration;
pub use stat_weaken_immune::stat_weaken_immune;
pub use stat_weaken_to::stat_weaken_to;
pub use stat_witch_killer::stat_witch_killer;
pub use stat_zombie_killer::stat_zombie_killer;
pub use std_map_int_bool_subscript::std_map_int_bool_subscript;
pub use std_map_int_int_from_list::std_map_int_int_from_list;
pub use std_map_int_int_from_list_2::std_map_int_int_from_list_2;
pub use std_map_int_int_insert_range::std_map_int_int_insert_range;
pub use std_map_int_maanim_subscript::std_map_int_maanim_subscript;
pub use std_map_int_maanim_subscript_2::std_map_int_maanim_subscript_2;
pub use std_map_int_map_subscript::std_map_int_map_subscript;
pub use std_map_int_map_subscript_2::std_map_int_map_subscript_2;
pub use std_map_int_shake_record_subscript::std_map_int_shake_record_subscript;
pub use std_map_int_string_subscript::std_map_int_string_subscript;
pub use std_map_int_vector_erase::std_map_int_vector_erase;
pub use std_map_int_vector_subscript::std_map_int_vector_subscript;
pub use std_map_string_string_count::std_map_string_string_count;
pub use std_map_string_string_find_equal::std_map_string_string_find_equal;
pub use std_stoi::std_stoi;
pub use std_string_concat_cstr::std_string_concat_cstr;
pub use std_string_from_cstr::std_string_from_cstr;
pub use std_vector_int_assign::std_vector_int_assign;
pub use std_vector_int_push_back::std_vector_int_push_back;
pub use std_vector_int_push_back_2::std_vector_int_push_back_2;
pub use surge_attack::surge_attack;
pub use surge_timing::SURGE_TIMING;
pub use surge_update::surge_update;
pub use talent_targets_trait::talent_targets_trait;
pub use targets_alien::targets_alien;
pub use targets_angel::targets_angel;
pub use targets_dark::targets_dark;
pub use targets_floating::targets_floating;
pub use targets_metal::targets_metal;
pub use targets_red::targets_red;
pub use targets_zombie::targets_zombie;
pub use trait_aku::trait_aku;
pub use trait_alien::trait_alien;
pub use trait_angel::trait_angel;
pub use trait_behemoth::trait_behemoth;
pub use trait_colossus::trait_colossus;
pub use trait_dark::trait_dark;
pub use trait_dojo::trait_dojo;
pub use trait_eva::trait_eva;
pub use trait_floating::trait_floating;
pub use trait_kaijin::trait_kaijin;
pub use trait_metal::trait_metal;
pub use trait_red::trait_red;
pub use trait_relic::trait_relic;
pub use trait_sage::trait_sage;
pub use trait_starred_alien::trait_starred_alien;
pub use trait_traitless::trait_traitless;
pub use trait_witch::trait_witch;
pub use trait_zombie::trait_zombie;
pub use transform_anchor::transform_anchor;
pub use transform_point::transform_point;
pub use turn_off_proc_badge::turn_off_proc_badge;
pub use turn_on_proc_badge::turn_on_proc_badge;
pub use unit_meets_restriction::unit_meets_restriction;
pub use upgrade_worker::upgrade_worker;
pub use validate_map_type::validate_map_type;
pub use wave_apply_hits::wave_apply_hits;
pub use wave_hit_cat_side::wave_hit_cat_side;
pub use wave_hit_enemy_side::wave_hit_enemy_side;
pub use wave_update::wave_update;
pub use worker_unlocked::worker_unlocked;
pub use xor_row51_get::xor_row51_get;
pub use xor_row_get::xor_row_get;
