
use crate::core::files::img015::*;

// UI List
pub const UI_TRAIT_ORDER: &[usize] = &[
    ICON_TRAIT_RED,
    ICON_TRAIT_FLOATING,
    ICON_TRAIT_BLACK,
    ICON_TRAIT_METAL,
    ICON_TRAIT_ANGEL,
    ICON_TRAIT_ALIEN,
    ICON_TRAIT_ZOMBIE,
    ICON_TRAIT_RELIC,
    ICON_TRAIT_AKU,
    ICON_TRAIT_TRAITLESS,
];