#![allow(dead_code)]
use std::fs;
use std::path::Path;

pub const ICON_SIZE: f32 = 40.0;

#[derive(Debug, Clone, Default)]
pub struct CatRaw {
    pub hitpoints: i32,
    pub knockbacks: i32,
    pub speed: i32,
    pub attack_1: i32,
    pub time_before_attack_1: i32,
    pub standing_range: i32,
    pub eoc1_cost: i32,
    pub cooldown: i32, 
    pub hitbox_position: i32,
    pub hitbox_width: i32,
    pub target_red: i32,
    pub unknown_11: i32,
    pub area_attack: i32,
    pub pre_attack_animation: i32,
    pub minimum_z_layer: i32,
    pub maximum_z_layer: i32,
    pub target_floating: i32,
    pub target_black: i32,
    pub target_metal: i32,
    pub target_traitless: i32,
    pub target_angel: i32,
    pub target_alien: i32,
    pub target_zombie: i32,
    pub strong_against: i32,
    pub knockback_chance: i32,
    pub freeze_chance: i32,
    pub freeze_duration: i32,
    pub slow_chance: i32,
    pub slow_duration: i32,
    pub resist: i32,
    pub massive_damage: i32,
    pub critical_chance: i32,
    pub attack_only: i32,
    pub double_bounty: i32,
    pub base_destroyer: i32,
    pub wave_chance: i32,
    pub wave_level: i32,
    pub weaken_chance: i32,
    pub weaken_duration: i32,
    pub weaken_to: i32,
    pub strengthen_threshold: i32,
    pub strengthen_boost: i32,
    pub survive: i32,
    pub metal: i32,
    pub long_distance_1_anchor: i32,
    pub long_distance_1_span: i32,
    pub wave_immune: i32,
    pub wave_block: i32,
    pub knockback_immune: i32,
    pub freeze_immune: i32,
    pub slow_immune: i32,
    pub weaken_immune: i32,
    pub zombie_killer: i32,
    pub witch_killer: i32,
    pub target_witch: i32,
    pub unknown_55: i32,        
    pub boss_wave_immune: i32,  
    pub unknown_57: i32,        
    pub kamikaze: i32,          
    pub attack_2: i32,
    pub attack_3: i32,
    pub time_before_attack_2: i32,
    pub time_before_attack_3: i32,
    pub attack_1_abilities: i32,
    pub attack_2_abilities: i32,
    pub attack_3_abilities: i32,
    pub unknown_66: i32,        
    pub soul_animation: i32,
    pub spawn_animation: i32,
    pub unknown_69: i32,
    pub barrier_breaker_chance: i32,
    pub warp_chance: i32,
    pub warp_duration: i32,
    pub warp_distance_minimum: i32,
    pub warp_distance_maximum: i32,
    pub warp_immune: i32,
    pub target_eva: i32,
    pub eva_killer: i32,
    pub target_relic: i32,
    pub curse_immune: i32,
    pub insanely_tough: i32,
    pub insane_damage: i32,
    pub savage_blow_chance: i32,
    pub savage_blow_boost: i32,
    pub dodge_chance: i32,
    pub dodge_duration: i32,
    pub surge_chance: i32,
    pub surge_spawn_anchor: i32, 
    pub surge_spawn_span: i32,   
    pub surge_level: i32,
    pub toxic_immune: i32,
    pub surge_immune: i32,
    pub curse_chance: i32,
    pub curse_duration: i32,
    pub mini_wave_flag: i32,
    pub shield_pierce_chance: i32,
    pub target_aku: i32,
    pub colossus_slayer: i32,
    pub soulstrike: i32,
    pub long_distance_2_flag: i32,
    pub long_distance_2_anchor: i32,
    pub long_distance_2_span: i32,
    pub long_distance_3_flag: i32,
    pub long_distance_3_anchor: i32,
    pub long_distance_3_span: i32,
    pub behemoth_slayer: i32,
    pub behemoth_dodge_chance: i32,
    pub behemoth_dodge_duration: i32,
    pub mini_surge_flag: i32,
    pub counter_surge: i32,
    pub conjure_unit_id: i32,
    pub sage_slayer: i32,
    pub metal_killer_percent: i32,
    pub explosion_chance: i32,
    pub explosion_spawn_anchor: i32,     
    pub explosion_spawn_span: i32, 
    pub explosion_immune: i32,
}

impl CatRaw {
    pub fn from_csv_line(csv_line: &str) -> Option<Self> {
        let line_parts: Vec<&str> = csv_line.split(',').collect();
        let get_int = |index: usize| line_parts.get(index).and_then(|s: &&str| s.trim().parse::<i32>().ok()).unwrap_or(0);
        let get_int_neg = |index: usize| line_parts.get(index).and_then(|s: &&str| s.trim().parse::<i32>().ok()).unwrap_or(-1);

        if line_parts.len() < 10 { return None; }

        Some(Self {
            hitpoints: get_int(0),
            knockbacks: get_int(1),
            speed: get_int(2),
            attack_1: get_int(3),
            time_before_attack_1: get_int(4) * 2,
            standing_range: get_int(5),
            eoc1_cost: get_int(6),
            cooldown: get_int(7) * 2,
            hitbox_position: get_int(8),
            hitbox_width: get_int(9),
            target_red: get_int(10),
            unknown_11: get_int(11),
            area_attack: get_int(12),
            pre_attack_animation: get_int(13),
            minimum_z_layer: get_int(14),
            maximum_z_layer: get_int(15),
            target_floating: get_int(16),
            target_black: get_int(17),
            target_metal: get_int(18),
            target_traitless: get_int(19),
            target_angel: get_int(20),
            target_alien: get_int(21),
            target_zombie: get_int(22),
            strong_against: get_int(23),
            knockback_chance: get_int(24),
            freeze_chance: get_int(25),
            freeze_duration: get_int(26),
            slow_chance: get_int(27),
            slow_duration: get_int(28),
            resist: get_int(29),
            massive_damage: get_int(30),
            critical_chance: get_int(31),
            attack_only: get_int(32),
            double_bounty: get_int(33),
            base_destroyer: get_int(34),
            wave_chance: get_int(35),
            wave_level: get_int(36),
            weaken_chance: get_int(37),
            weaken_duration: get_int(38),
            weaken_to: get_int(39),
            strengthen_threshold: get_int(40),
            strengthen_boost: get_int(41),
            survive: get_int(42),
            metal: get_int(43),
            long_distance_1_anchor: get_int(44),
            long_distance_1_span: get_int(45),
            wave_immune: get_int(46),
            wave_block: get_int(47),
            knockback_immune: get_int(48),
            freeze_immune: get_int(49),
            slow_immune: get_int(50),
            weaken_immune: get_int(51),
            zombie_killer: get_int(52),
            witch_killer: get_int(53),
            target_witch: get_int(54),
            unknown_55: get_int_neg(55),
            boss_wave_immune: get_int_neg(56),
            unknown_57: get_int_neg(57),
            kamikaze: get_int(58),
            attack_2: get_int(59),
            attack_3: get_int(60),
            time_before_attack_2: get_int(61),
            time_before_attack_3: get_int(62),
            attack_1_abilities: get_int(63),
            attack_2_abilities: get_int(64),
            attack_3_abilities: get_int(65),
            unknown_66: get_int_neg(66),
            soul_animation: get_int(67),
            spawn_animation: get_int(68),
            unknown_69: get_int(69),
            barrier_breaker_chance: get_int(70),
            warp_chance: get_int(71),
            warp_duration: get_int(72),
            warp_distance_minimum: get_int(73),
            warp_distance_maximum: get_int(74),
            warp_immune: get_int(75),
            target_eva: get_int(76),
            eva_killer: get_int(77),
            target_relic: get_int(78),
            curse_immune: get_int(79),
            insanely_tough: get_int(80),
            insane_damage: get_int(81),
            savage_blow_chance: get_int(82),
            savage_blow_boost: get_int(83),
            dodge_chance: get_int(84),
            dodge_duration: get_int(85),
            surge_chance: get_int(86),
            surge_spawn_anchor: get_int(87) / 4,
            surge_spawn_span: get_int(88) / 4,
            surge_level: get_int(89),
            toxic_immune: get_int(90),
            surge_immune: get_int(91),
            curse_chance: get_int(92),
            curse_duration: get_int(93),
            mini_wave_flag: get_int(94),
            shield_pierce_chance: get_int(95),
            target_aku: get_int(96),
            colossus_slayer: get_int(97),
            soulstrike: get_int(98),
            long_distance_2_flag: get_int(99),
            long_distance_2_anchor: get_int(100),
            long_distance_2_span: get_int(101),
            long_distance_3_flag: get_int(102),
            long_distance_3_anchor: get_int(103),
            long_distance_3_span: get_int(104),
            behemoth_slayer: get_int(105),
            behemoth_dodge_chance: get_int(106),
            behemoth_dodge_duration: get_int(107),
            mini_surge_flag: get_int(108),
            counter_surge: get_int(109),
            conjure_unit_id: get_int(110),
            sage_slayer: get_int(111),
            metal_killer_percent: get_int(112),
            explosion_chance: get_int(113),
            explosion_spawn_anchor: get_int(114) / 4,
            explosion_spawn_span: get_int(115) / 4,
            explosion_immune: get_int(116),
        })
    }
    
    pub fn attack_cycle(&self, animation_frames: i32) -> i32 {
        let mut effective_foreswing = self.pre_attack_animation;
        
        if self.attack_3 > 0 && self.time_before_attack_3 > 0 {
            effective_foreswing = self.time_before_attack_3;
        } 
        else if self.attack_2 > 0 && self.time_before_attack_2 > 0 {
            effective_foreswing = self.time_before_attack_2;
        }

        let cooldown_frames = self.time_before_attack_1.saturating_sub(1);
        
        (effective_foreswing + cooldown_frames).max(animation_frames)
    }

    pub fn effective_cooldown(&self) -> i32 {
        (self.cooldown - 264).max(60)
    }
}

pub fn load_from_id(cat_id: i32) -> Option<CatRaw> {
    let file_path_str = format!("game/cats/{:03}/unit{:03}.csv", cat_id, cat_id + 1);
    let path_object = Path::new(&file_path_str);
    
    if path_object.exists() {
        if let Ok(file_content) = fs::read_to_string(path_object) {
            if let Some(first_line) = file_content.lines().next() {
                return CatRaw::from_csv_line(first_line);
            }
        }
    }
    None
}